### ISSUE TITLE
404 Adler

### ISSUE THREAD

**Issue by DerZade** [gruppe-adler/gruppe-adler.de#1]
https://github.com/DerZade/gruppe-adler.de/blob/master/src/assets/error/404.png is only a placeholder and has to be replaced.

**Comment by nomisum** [comment]
![404](https://user-images.githubusercontent.com/500164/61582674-f55e8080-ab2d-11e9-855f-e74ff89aed52.png)

**Comment by nomisum** [comment]
![404](https://user-images.githubusercontent.com/500164/61582731-d1e80580-ab2e-11e9-8b4e-eb5ebf2b2010.png)
