### ISSUE TITLE
Fix Footer Image Sizes 

### ISSUE THREAD

**Issue by DerZade** [gruppe-adler/gruppe-adler.de#6]
- YouTube looks big in proportion to the rest of the logos.
- Twitter Font looks rather small

![](https://i.imgur.com/RxQN0zy.png)

**Comment by nomisum** [comment]
should be harmonized now https://github.com/gruppe-adler/gruppe-adler.de/commit/ef13e1193e51e03c8b3d85ac12dbdf090d7395bd
